
services:
  favoritefood:
    image: favoritefood-wordpress
    build: .
    container_name: favoritefood-wordpress
    restart: always
    ports:
      - "3680:80"
    env_file: .env
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - sigma-net
    depends_on:
      - favoritefood-db

  favoritefood-db:
    image: mariadb:10.6
    container_name: favoritefood-db
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:3654:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sigma-net

volumes:
  db_data:

networks:
  sigma-net:
    external: true
